name: Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker-hub:
    name: 'Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Install dependencies
        run: |
          go version
          go install github.com/davidrjonas/semver-cli@latest

      - uses: actions/checkout@v3

      - name: Checkout new version
        run: task clone

      - name: Prepare version
        run: task prepare

      - name: CentOS
        run: |
          task build:centos
          task push:centos

      - name: Build Debian
        run: |
          task build:debian
          task push:debian

  github-registry:
    name: 'GitHub Container Registry'
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Install dependencies
        run: |
          go version
          go install github.com/davidrjonas/semver-cli@latest

      - uses: actions/checkout@v3

      - name: Checkout new version
        run: task clone

      - name: Prepare version
        run: task prepare

      - name: CentOS
        run: |
          task build:centos IMAGE=ghcr.io/${{ github.repository_owner }}/activemq-artemis
          task push:centos IMAGE=ghcr.io/${{ github.repository_owner }}/activemq-artemis

      - name: Debian
        run: |
          task build:debian IMAGE=ghcr.io/${{ github.repository_owner }}/activemq-artemis
          task push:debian IMAGE=ghcr.io/${{ github.repository_owner }}/activemq-artemis
